# Generated by Django 3.0.6 on 2020-09-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=3000)),
            ],
        ),
    ]
